### ISSUE TITLE
API URL

### ISSUE THREAD

**Issue by rasos** [samirsayyad/ep_rocketchat#1]
It seems that this URL as speicified in the README does not lead to a valid endpoint: 

           https://yourEtherpadInstance.com/static/pluginfw/ep_rocketchat/rocket_chat_auth_get

Shouldn't that be something like 

          https://yourEtherpadInstance.com/static/plugins//ep_rocketchat/rocketChat/clients/restClient.js

I suppose that need to be put in the RocketChat Accounts Settings as `Iframe URL` and also to `API URL` with `Api Method`  `GET`.

**Comment by samirsayyad** [comment]
Hi 
can you share the curl result with me?

**Comment by samirsayyad** [comment]
Fixed.
Find it [here](https://github.com/samirsayyad/ep_rocketchat/blob/main/README.md).
